#!/usr/bin/perl -w

##############################################################################
# Copyright 2003 Jonathan Cohen, Nat Duca, David Luebke, Brenden Schubert    #
#                Johns Hopkins University and University of Virginia         #
##############################################################################
# This file is distributed as part of the GLOD library, and as such, falls   #
# under the terms of the GLOD public license. GLOD is distributed without    #
# any warranty, implied or otherwise. See the GLOD license for more details. #
#                                                                            #
# You should have recieved a copy of the GLOD Open-Source License with this  #
# copy of GLOD; if not, please visit the GLOD web page,                      #
# http://www.cs.jhu.edu/~graphics/GLOD/license for more information          #
##############################################################################

if(scalar(@ARGV) != 1) {
    printf("Usage: htmlstrip <filename>\n\n");
    exit 0;
}

open(IN, $ARGV[0]) || die($!);
while(<IN>) {
    last if(/\<BODY\>/);
}

while(<IN>) {
    last if(/\<\/BODY\>/);
    print $_;
}
close(IN);
